#!/usr/bin/env python3
"""Collect binary dependency notices for the union of release targets (stdlib only)."""
import argparse
import ast
import os
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
GO = os.environ.get("ELEPHANT_GO", "go")
OUTPUT = ROOT / "THIRD_PARTY_NOTICES"
MODULE_TEMPLATE = "{{with .Module}}{{.Path}}\t{{.Version}}\t{{.Dir}}{{end}}"


def go_output(*args, env=None):
    return subprocess.check_output([GO, *args], cwd=ROOT, env=env, text=True).rstrip("\n")


def release_targets():
    # Importing build_release would build archives; read only its literal TARGETS.
    tree = ast.parse((ROOT / "scripts/build_release.py").read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "TARGETS"
            for target in node.targets
        ):
            return ast.literal_eval(node.value)
    raise ValueError("No literal TARGETS found in scripts/build_release.py")


def linked_modules():
    main_module = go_output("list", "-m", "-f", "{{.Path}}")
    modules = {}
    for goos, goarch in release_targets():
        env = dict(os.environ, GOOS=goos, GOARCH=goarch, CGO_ENABLED="0")
        rows = go_output("list", "-deps", "-f", MODULE_TEMPLATE, "./cmd/elephant", env=env)
        if any(row and not row.split("\t")[-1] for row in rows.splitlines()):
            go_output("mod", "download", env=env)
            rows = go_output("list", "-deps", "-f", MODULE_TEMPLATE, "./cmd/elephant", env=env)
        for row in rows.splitlines():
            if not row:
                continue
            path, version, directory = row.split("\t")
            if path == main_module:
                continue
            if not version or not directory:
                raise ValueError(f"Missing version or module directory for {path}")
            key = (path, version)
            if key in modules and modules[key] != pathlib.Path(directory):
                raise ValueError(f"Conflicting module directories for {path} {version}")
            modules[key] = pathlib.Path(directory)
    return modules


def notice_files(module, directory):
    files = []
    for path in directory.iterdir():
        name = path.name.upper()
        if path.is_file() and (
            name.startswith(("LICENSE", "COPYING", "NOTICE")) or name == "PATENTS"
        ):
            files.append(path)
    # SQLite's dedication is named SQLITE-LICENSE, not LICENSE*. libc's
    # LICENSE-3RD-PARTY.md is already collected above. Testdata is not linked.
    if module == "modernc.org/sqlite":
        files.append(directory / "SQLITE-LICENSE")
    if not files:
        raise ValueError(f"No top-level license/notice files for {module}")
    return sorted(files, key=lambda path: path.name)


def spdx_guess(text):
    lower = text.lower()
    if "permission is hereby granted, free of charge" in lower:
        return "MIT"
    if "redistribution and use in source and binary forms" in lower:
        if "neither the name" in lower or "neither the names" in lower:
            return "BSD-3-Clause"
        return "BSD-2-Clause"
    if "sqlite is public domain" in lower:
        return "LicenseRef-Public-Domain"
    return "NOASSERTION"


def section(title, files):
    texts = [(name, path.read_text(encoding="utf-8")) for name, path in files]
    primary = next((text for name, text in texts if name.upper() == "LICENSE"), "")
    result = [f"=== {title} ===\n", f"SPDX license identifier (guess): {spdx_guess(primary)}\n\n"]
    for name, text in texts:
        result.append(f"--- {name} ---\n")
        result.append(text)
        if not text.endswith("\n"):
            result.append("\n")
        result.append("\n")
    return "".join(result)


def generate():
    modules = linked_modules()
    result = [
        "THIRD-PARTY NOTICES\n"
        "Generated by scripts/generate_notices.py; do not edit by hand.\n"
        "Includes modules linked by ./cmd/elephant across all release targets\n"
        "with CGO_ENABLED=0, their bundled notices, and the Go runtime license.\n"
        "SPDX identifiers are best-effort guesses for the primary module license;\n"
        "the full texts below, including bundled third-party terms, are authoritative.\n\n"
    ]
    for (module, version), directory in sorted(modules.items()):
        files = [(path.name, path) for path in notice_files(module, directory)]
        result.append(section(f"{module} {version}", files))
    goroot = pathlib.Path(go_output("env", "GOROOT"))
    license_path = goroot / "LICENSE"
    # Homebrew moves LICENSE from GOROOT=.../libexec to the formula directory.
    if not license_path.is_file() and goroot.name == "libexec":
        license_path = goroot.parent / "LICENSE"
    if not license_path.is_file():
        raise ValueError(f"Go toolchain LICENSE not found under {goroot}")
    result.append(section("Go standard library/runtime", [("LICENSE", license_path)]))
    return "".join(result)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if committed notices are stale")
    args = parser.parse_args()
    try:
        expected = generate().encode("utf-8")
        if args.check:
            if not OUTPUT.is_file() or OUTPUT.read_bytes() != expected:
                print(
                    "THIRD_PARTY_NOTICES differs from generated notices. Run "
                    "python3 scripts/generate_notices.py, then "
                    "git diff -- THIRD_PARTY_NOTICES to review the changes.",
                    file=sys.stderr,
                )
                return 1
            print("THIRD_PARTY_NOTICES is up to date.")
        else:
            OUTPUT.write_bytes(expected)
            print("Generated THIRD_PARTY_NOTICES.")
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f"Cannot generate notices: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
